name: XenServer Ocaml Training
markdown: kramdown
pygments: true
baseurl: /ocaml-training

defaults:
  - 
    scope:
      path: notebooks
    values:
      layout: iocamljs
      kernel: min
      tutorial_notebook: true
